# Copyright 2023 Rob Spoor
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release site

on:
  push:
    tags: ['v[0-9]+.[0-9]+*']

permissions:
  contents: write

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: '22.x'
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Run TypeDoc
        run: npm run typedoc
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
          retention-days: 1

  deploy-site:
    runs-on: ubuntu-latest
    needs: ['build-site']
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
      - uses: actions/download-artifact@v5
        with:
          name: docs
          path: docs
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          commit-message: 'Updated for version ${{ github.ref_name }}'
